title: Umar Jamil
author: Umar Jamil
description: ML Engineer and Researcher
url: https://umarjamil.org
locale: en_US

theme: minima
minima:
  skin: dark

permalink: pretty

show_excerpts: false

twitter_username: hkproj
youtube_username: "@umarjamilai"
github_username: hkproj
linkedin_username: ujamil
